name:                persistent-playground
version:             0.1.0.0
github:              "githubuser/persistent-playground"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/persistent-playground#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers
- esqueleto
- freer-simple
- hedis
- lens
- monad-logger
- mtl
- natural-transformation
- persistent
- persistent-postgresql
- persistent-sqlite
- persistent-template
- resourcet
- servant
- servant-client
- servant-server
- text
- time
- transformers
- warp

library:
  source-dirs: src
  exposed-modules:
  - API
  - APIEff
  - APIMonad
  - Cache
  - Database
  - Eff.Cache
  - Eff.Database
  - Eff.Utils
  - Errors
  - Monad.App
  - Monad.Cache
  - Monad.Database
  - Types
  - Schema

executables:
  persistent-playground-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - persistent-playground

tests:
  persistent-playground-test:
    main:                APISpec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - http-client
    - http-client-tls
    - monad-logger
    - mtl
    - network
    - persistent-playground
    - servant-client
