name:                haskell-heroku-playground
version:             0.1.0.0
github:              "githubuser/haskell-heroku-playground"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-heroku-playground#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- freer-simple
- monad-logger
- mtl
- servant
- servant-server
- text
- transformers
- unordered-containers
- warp

library:
  source-dirs: src

executables:
  haskell-heroku-playground-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-heroku-playground

tests:
  haskell-heroku-playground-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-heroku-playground
