name:                twilio-integration
version:             0.1.0.0
github:              "githubuser/twilio-integration"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/twilio-integration#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- freer-simple
- hailgun
- http-api-data
- http-client-tls
- lens
- monad-logger
- mtl
- persistent
- persistent-postgresql
- persistent-template
- resourcet
- resource-pool
- servant
- servant-client
- servant-server
- text
- transformers
- twilio
- unordered-containers
- wai
- warp

library:
  source-dirs: src
  exposed-modules:
    - TwilioServer
    - Server
    - Email
    - Mailchimp
    - Eff.Email
    - Eff.SMS
    - Eff.Database

executables:
  twilio-integration-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twilio-integration

tests:
  twilio-integration-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twilio-integration
